### ISSUE TITLE
Reflection: Find the target model of a through association

### ISSUE THREAD

**Issue by mbrock** [nviennot/nobrainer#114]
While working on porting `rails_admin` to NoBrainer, I stumbled across the need to determine whether an association is polymorphic.

For regular non-through associations, I simply do `association.target_model.is_polymorphic`.

However, a through-association doesn't have a `target_model`, but instead a `target_association`.

It's not clear to me how I would find the actual targetted model through this.

In the example I'm working with—a HABTM-like setup—I have:

```ruby
class Team
  include NoBrainer::Document
  has_many :team_fans
  has_many :fans, through: :team_fans
end

class Fan
  include NoBrainer::Document
  has_many :team_fans
  has_many :teams, through: :team_fans
end

class TeamFan
  include NoBrainer::Document
  belongs_to :team
  belongs_to :fan
end
```

To give a clearer idea of what I'm trying to do, here's what I'm looking at in `irb`:

```
(byebug) association
#<NoBrainer::Document::Association::HasManyThrough::Metadata:0x00000002eec968 @owner_model=Team, @target_name=:fans, @options={:through=>:team_fans}>
(byebug) association.target_model
NoMethodError Exception: undefined method `target_model' for #<NoBrainer::Document::Association::HasManyThrough::Metadata:0x00000002eec968>
nil
(byebug) association.through_associations
NoMethodError Exception: undefined method `through_associations' for #<NoBrainer::Document::Association::HasManyThrough::Metadata:0x00000002eec968>
nil
(byebug) association.through_association
#<NoBrainer::Document::Association::HasMany::Metadata:0x00000002ecc730 @owner_model=Team, @target_name=:team_fans, @options={}>
(byebug) association.through_association.target_model
TeamFan
```

I'm looking around for a way to access the `Fan` model. Maybe I'm missing something obvious? :)

**Comment by nviennot** [comment]
So you want to know the target_model of a has many through association if I understand correctly?

If so, you are not missing anything, there is no code traverse the associations like that.
The only code that traverses recursively the associations is the eager loading logic, which the has many through leverages to do its magic.

Let me add a bit of code for that.

**Comment by nviennot** [comment]
You can now call `target_model` on a has_many_through :)

**Comment by nviennot** [comment]
Btw, NoBrainer does not support polymorphic associations at the moment since you mentioned it.
e.g. `belongs_to` can never point to an arbitrary model by using a second type foreign key.

**Comment by mbrock** [comment]
Thanks again! I'm not sure whether this polymorphic association business will be a problem for me in practice. We'll see.
