### ISSUE TITLE
has_many association order – or, association scopes?

### ISSUE THREAD

**Issue by mbrock** [nviennot/nobrainer#115]
While porting the dummy test app of `rails_admin`, I ran into a discrepancy with Mongoid: namely, how to port the following.

```ruby
class Team
  include Mongoid::Document
  has_many :players, order: :_id.desc
end
```

What do you think about supporting scopes on `has_many` associations? For example:

```ruby
class Team
  include Mongoid::Document
  has_many :players { order(id: :desc) }
end
```

I'm not very familiar with the NoBrainer internals, but I had a hunch that with the recent change to support chained scopes (fc886221920bf0d398c67b0c81b81e2fea40f7fc), it might be easy?

**Comment by mbrock** [comment]
(This might be a far-fetched idea; otherwise, just allowing an `order` parameter seems reasonable, too.)

**Comment by nviennot** [comment]
Yeah I can do that, but it might not be as trivial as it sound, we'll see.

The API will look like `has_many :xxx, :scope => where(xxx)`

**Comment by nviennot** [comment]
However, when using a scope, you don't be able to use `:dependent => :destroy`, otherwise, it's not obvious what should happen.

**Comment by mbrock** [comment]
Fair enough. I would be happy with a simple `order` option on `has_many`, but scoped associations seems like a pretty cool feature.

Maybe as a future feature, there could be two other options for `dependent`, something like `:destroy_all` and `:destroy_scoped`?

**Comment by nviennot** [comment]
Feels like unnecessary complications. I don't see why you would want to destroy only a subset of your association. For weird cases like this, one can always do a `before_destroy { my_weird_scope.destroy_all }` or whatever

**Comment by mbrock** [comment]
Agreed.

**Comment by nviennot** [comment]
All done. Note that you can only pass lambdas to the scope option. A bare `where` won't work.
This lambda will be evaluated in the context of the target model, so you can use its named scopes.
Example:

```ruby
class Post
  has_many :admin_comments, :class_name => 'Comment', :scope => ->{ from_admin }
end

class Comments
  belongs_to :post

  # we could also use the scope keyword
  def self.from_admin
    where(:admin_author => true)
  end
end
```

**Comment by mbrock** [comment]
Very cool! :)
fre 9 jan 2015 kl. 18:16 skrev Nicolas Viennot <notifications@github.com>:
