### ISSUE TITLE
Type exception on save? when using uniqueness validation

### ISSUE THREAD

**Issue by mbrock** [nviennot/nobrainer#117]
Hello!

Here is a small program that causes an `InvalidType` exception when using `save?'. The reason is that there is a uniqueness validation on the relevant field, which assumes that the value is castable.

```ruby
require 'nobrainer'

NoBrainer.configure { |c| c.app_name = 'nobrainer_test_uniqueness_validation' }
NoBrainer.drop!

class X
  include NoBrainer::Document
  field :i, type: Integer
  validates_uniqueness_of :i
end

x = X.new i: "foo"
x.save?
```

I am not very familiar with validations and I'm not sure what I would expect. But it seems wrong that `save?` throws an exception.

**Comment by nviennot** [comment]
It will, because `"foo"` is not an integer.

You can also use `save` instead of `save?` and you will see that the exception is `NoBrainer::Error::InvalidType: I should be a integer`.
So I don't think this has anything to do with the uniqueness validator.

**Comment by mbrock** [comment]
Sorry, yes, to clarify: without the uniqueness validator, `save?` does not throw, but instead leaves a `"should be an integer"` message in `x.errors`.

**Comment by mbrock** [comment]
For context, my application has an explicit `numericality` validator to make sure that the field in question is a number, and also a scoped uniqueness validation. The CRUD interface wants to use `save?` and then show the errors to the user. But now, if the user accidentally submits `foo` as the number, she will get a stack trace instead of a validation error.

**Comment by nviennot** [comment]
The type checking in nobrainer works like validations, so if the CRUD interface uses `save?`, then you can use `x.errors.full_messages` to get the type error. A validation error on `i` will be set.

Using the `Integer` type implies some numericality validator defined as the following:
````
Integers are accepted.
Strings are converted to integers only when the resulting integer can be converted back to the original stripped string. For example, " -4 " and "+3" are valid, but "4f" or "" are not.
Floats are accepted when their values matches exactly an integer.
Any other value is ignored, and a validation error is added.
```
see http://nobrainer.io/docs/types/

The validator that you add on top of nobrainer's internal type checking is extra. (Maybe useful if you want to use a positive constraint or whatnot).

FYI, the same rules apply on `where()` queries when it comes to type safetly. e.g. `User.where(i: 'foo')` will raise an InvalidType.

What was your expectation when you specified `:type => Integer`?

**Comment by mbrock** [comment]
My expectation is that `save?` will never raise an exception for field type errors. I do expect `save` without the question mark to raise, of course. If I remove the uniqueness validation from my example, then everything works as I expect.

**Comment by nviennot** [comment]
Sorry, I didn't understand your issue sooner. Fixed!

**Comment by mbrock** [comment]
Excellent, thank you! :+1:
