### ISSUE TITLE
rescuing DocumentInvalid on save

### ISSUE THREAD

**Issue by pedram-tiv** [nviennot/nobrainer#125]
If document does not pass validation during save, NoBrainer::Error::DocumentInvalid is  raised 
https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/document/persistance.rb#L103,
in Rails this would cause an error page to be displayed. 
In ActiveRecord a flash error message is displayed notifying the user of the validation error, for an out of the box behaviour this seems to me more helpful. ActiveRecord does this by rescuing the exception on save. see:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L123

Of course in the controller we can implement the rescue, for example by:
def create
    @content = Content.new(content_params)
    @content.save
    respond_with(@content)
rescue NoBrainer::Error::DocumentInvalid
      respond_with(@content)
end

Would it make sense to follow how active record behaves? This is not an issue, but rather a choice in implementation. 

thanks.

**Comment by ajselvig** [comment]
The equivalent to ActiveRecord's _.save_ in NoBrainer is _.save?_, whereas _.save_ in NoBrainer is the same as _.save!_ in ActiveRecord (which is why the exception is raised).

**Comment by pedram-tiv** [comment]
thanks for the reply. Oh yes, saw that in the docs.
Would it make sense to have the generator generate .save? instead?

**Comment by ajselvig** [comment]
You're talking about the built-in rails scaffold generator?

**Comment by pedram-tiv** [comment]
Yes, I was. I will look into this and update thread if needed.
thanks for the comments.

**Comment by pedram-tiv** [comment]
@nviennot sure.
