### ISSUE TITLE
Shouldn't before_validation go before validations and before_save?

### ISSUE THREAD

**Issue by dmitry** [nviennot/nobrainer#126]
For me it looks a little bit strange when `before_save` callback is located before the `before_validation`. Mongoid and ActiveRecord have `before_validation` before all the `*_save/create/destroy` callbacks, and from the experience it's a correct order of the callbacks.

Callback order in different ORMs:

Nobrainer: http://nobrainer.io/docs/callbacks/
Mongoid: http://mongoid.org/en/mongoid/docs/callbacks.html
ActiveRecord: http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html

What was the purpose to put `before_save` before the `before_validation`?
As I read somewhere nobrainer tries to be drop-in replacement for mongoid, but isn't at least this most common used behaviour differs?

**Comment by nviennot** [comment]
From experience, the ActiveRecord/Mongoid way of calling the validation callbacks is incorrect:
Developers typically mutate the data in `before_save` callbacks, so it makes sense that validations are performed right before saving.

**Comment by nviennot** [comment]
Example: https://github.com/gitlabhq/gitlabhq/blob/master/app/models/note.rb#L57
which ends up doing: https://github.com/gitlabhq/gitlabhq/blob/master/app/models/note.rb#L287
which sets an attribute *after* the validations were run, and so this attribute will not be properly validated.

**Comment by nviennot** [comment]
Can you elaborate why having `before_validation` run before `before_save` is better? Can you show a piece of code that relies on this specific order?

**Comment by dmitry** [comment]
For example, we have Enquiry and User model. enquiry has one user. User and Enquiry have `phone` fields. Now we are going to create Enquiry, through `enquiry.create_user(phone: '123')`. While creation we would like to update user`s phone, but it should be updated only if validation is valid. I don't know anything about transactions in rethinkdb and nobrainer yet, but even if enquiry will not be able to save in ActiveRecord will be raisen an exception. So basically, I think nobrainer should follow the same behaviour as ActiveRecord and MongoId have.

**Comment by nviennot** [comment]
Can you write the corresponding code? I'll understand better :) Thank you :)

**Comment by dmitry** [comment]
I've made few mistakes in previous post, because I can't find real use case, but I remember I had few of them and they wasn't teoretical.

```
class Enquiry
  belongs_to :user

  before_validation do
    unless address.present?
      self.address = user.address
    end
  end

  validates :name, :address, presence: true

  before_create do
    self.user.phone = phone
  end
end

class User
  has_many :enquiries
end

# lets suppose user have address or not
User.first.enquiries.create(phone: '123', address: '')
```

**Comment by nviennot** [comment]
Your example doesn't really demonstrate that running validations before the `before_create` is better. Unless I'm missing something.

**Comment by dmitry** [comment]
What about this example: https://github.com/rmm5t/strip_attributes/blob/master/lib/strip_attributes.rb#L8 ?

**Comment by nviennot** [comment]
I'd argue that this demonstrate the need to have the before validation callbacks to run *after* the before_save: when someone changes an attribute in a before_save callback, then the attribute striping can be performed on the changes.

Further, your example does not really show that the order of callback matters.

**Comment by nviennot** [comment]
discussion is going here: https://github.com/nviennot/nobrainer/issues/142
