### ISSUE TITLE
Lots of warnings about uninitialized variables

### ISSUE THREAD

**Issue by jdrago999** [nviennot/nobrainer#128]
Hi -

I'm using nobrainer on ruby 2.0.0p384 and I keep seeing a lot of warnings about '@pending_type_errors' and similar.

Output:

/var/lib/gems/2.0.0/gems/nobrainer-0.13.1/lib/no_brainer/document/types.rb:154: warning: instance variable @pending_type_errors not initialized
...
/var/lib/gems/2.0.0/gems/ruby-protocol-buffers-1.6.1/lib/protocol_buffers/runtime/field.rb:180: warning: instance variable @parent_for_notify not initialized
...
/var/lib/gems/2.0.0/gems/ruby-protocol-buffers-1.6.1/lib/protocol_buffers/runtime/field.rb:132: warning: instance variable @args not initialized
...
/var/lib/gems/2.0.0/gems/ruby-protocol-buffers-1.6.1/lib/protocol_buffers/runtime/field.rb:162: warning: instance variable @parent_for_notify not initialized
...
/var/lib/gems/2.0.0/gems/ruby-protocol-buffers-1.6.1/lib/protocol_buffers/runtime/field.rb:132: warning: instance variable @optargs not initialized
...
/var/lib/gems/2.0.0/gems/nobrainer-0.13.1/lib/no_brainer/connection.rb:11: warning: method redefined; discarding old parsed_uri
...
/var/lib/gems/2.0.0/gems/rethinkdb-1.12.0.2/lib/net.rb:294: warning: instance variable @listener not initialized
/var/lib/gems/2.0.0/gems/rethinkdb-1.12.0.2/lib/net.rb:252: warning: instance variable @socket not initialized
/var/lib/gems/2.0.0/gems/rethinkdb-1.12.0.2/lib/net.rb:328: warning: instance variable @listener not initialized
/var/lib/gems/2.0.0/gems/rethinkdb-1.12.0.2/lib/net.rb:142: warning: instance variable @auto_reconnect not initialized
...
(and so on and so forth)

Are you not seeing these?  If it's just my setup, then that's one thing, but it seems odd to have so many warnings about simple things like initializing variables.

**Comment by nviennot** [comment]
I'm not seeing this, but apparently, it would do this when you run ruby with `-W2`.
I would ignore these warnings.

**Comment by jdrago999** [comment]
I upgraded to the latest version and no longer see the warnings.
