### ISSUE TITLE
Rails Completed log improvement

### ISSUE THREAD

**Issue by zedtux** [nviennot/nobrainer#130]
This issue is an improvement proposal.

When a Rails application is running and writting logs, there is the famous line

    Completed 200 OK in 247ms (Views: 86.0ms | ActiveRecord: 110.9ms)

This line could be improved by adding Nobrainer after ActiveRecord like so:

    Completed 200 OK in 277ms (Views: 86.0ms | ActiveRecord: 110.9ms | Nobrainer: 30ms)

**Comment by zedtux** [comment]
@nviennot can you please tell if this looks good idea for you ?

**Comment by nviennot** [comment]
Yes it's a good idea, I haven't got the time to implement it yet :)

**Comment by nviennot** [comment]
Done.

You'll get a break down that accounts for read and write queries separately:

```
Completed 200 OK in 151ms (Views: 121.5ms | NoBrainer: 29.4ms (read), 15.3ms (write))
```

**Comment by zedtux** [comment]
Awesome !! I will give it a try as soon as possible. The way you did it rocks !
