### ISSUE TITLE
Setting belongs_to ids to nil when an empty string is set

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#133]
When using url encoded for submissions, there's no real way to represent a "null" value. A common pattern is to have a dropdown for the possible options of a belongs_to relationship, with an empty option for "none", which gets transmitted as an empty string.

The problem is that NoBrainer faithfully stores the foreign key as an empty string. I believe that it would be better to store that field as null. Storing an empty string is technically incorrect, since [there could actually be a record with an empty string as an id](https://github.com/nviennot/nobrainer/issues/118). 

Is this possible?

**Comment by nviennot** [comment]
I don't have this problem. Can you write a little test case?

**Comment by ajselvig** [comment]
```ruby
require 'nobrainer'

NoBrainer.configure do |config|
  config.rethinkdb_url          = 'rethinkdb://localhost/nobrainer_playground'
  config.logger                 = Logger.new $stdout
end

class Foo
  include NoBrainer::Document

  has_many :bars
end

class Bar
  include NoBrainer::Document

  belongs_to :foo
end

Foo.delete_all
Bar.delete_all

foo = Foo.create
bar = Bar.create foo_id: foo.id

bar.update_attributes foo_id: ''
bar.update_attributes foo_id: nil
```

The first update_attributes executes:

```
r.table("bars").get("1oVxWr6AdJuuGl").update {|var_1| {"foo_id" => ""}}
```

and the second executes:

```
r.table("bars").get("1oVxWr6AdJuuGl").update {|var_1| {"foo_id" => nil}}
```

I am proposing that they both execute the latter query. This is because it's a common pattern to be assigning the foo_id from a form like:

```html
<select name="foo_id">
    <option value="">None Selected</option>
    <option value="1oVzCCd2GE5pEP">Foo 1</option>
    ... other options
</select>
```

**Comment by nviennot** [comment]
add `:required => true` on the belongs to association

**Comment by nviennot** [comment]
oops no, nevermind. let me think about this

**Comment by ajselvig** [comment]
But it's not a required association, that's the whole point of having the empty option.

**Comment by nviennot** [comment]
What does your controller code look like?

**Comment by nviennot** [comment]
You can add this in your model to have the behavior that you want:

```
def foo_id=(value)
  super(value.presence)
end
```

I'm a little uncomfortable to do it by the ORM, because then you'd want this feature for any attributes? Why restrict this feature with foreign keys?

**Comment by ajselvig** [comment]
The controller is totally normal, just assigning the form parameters to the model object:

```ruby
def update
  bar = Bar.find params[:id]
  bar.update_attributes params[:bar]
end
```

> because then you'd want this feature for any attributes? 
Certainly not. Storing empty strings is reasonable behavior for regular string fields.

> Why restrict this feature with foreign keys?
Foreign keys are fundamentally different than string fields. They are supposed to always contain the id of an existing record or "nothing" (nil). 

In the same vein, this also works fine:

```ruby
bar.update_attributes foo_id: 'something'
```

but is also equally non-sensical.

**Comment by nviennot** [comment]
I'd solve this in two ways:

1) Either add this in your model:

```ruby
def foo_id=(value)
  super(value.presence)
end
```

You enforce the translation at the model level.

2) Or in your controller:

```ruby
  bar.update_attributes(:foo_id => params[:foo_id].presence)
```

---

To avoid issues with `bar.update_attributes foo_id: 'invalid'`, You can do something like this:

```ruby
belongs_to :foo, :validates => {:presence => true, :if => ->{ foo_id.present? }}
```

It's pretty ugly, but I don't want to do this behavior by default. What would be a good shorthand to specify this?

**Comment by nviennot** [comment]
Actually, maybe it's a good default. If you don't want it, it's probably because you are importing data in some ways. You might be better of with doing `save(validate: false)`.
Let me implement that. It should be quick.

**Comment by ajselvig** [comment]
All I had to do was not respond for three minutes!

**Comment by nviennot** [comment]
Foreign keys are always validated now. If you don't want this behavior, you can pass `validates: false` on the `belongs_to` declaration.

**Comment by ajselvig** [comment]
So, this is definitely better but it still doesn't solve the original
problem: ids that get sent to null on the web side get transmitted as an
empty string and assigned on the server. This, of course, causes the
validation to fail.

If you don't want to bake a concept of 'empty string == nil id' into
NoBrainer, can you suggest the simplest way to monkey patch NoBrainer to
add this behavior?

**Comment by nviennot** [comment]
You can add this in an initializer:

```ruby
module ForeignKeyPresence
  def hook
    super
    fk_setter = "#{self.foreign_key}="
    owner_model.inject_in_layer :transformations do
      define_method(fk_setter) { |value| super(value.presence) }
    end
  end

  NoBrainer::Document::Association::BelongsTo::Metadata.send(:include, self)
end
```

**Comment by ajselvig** [comment]
That worked. thanks!
