### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by lobo-tuerto** [nviennot/nobrainer#134]
I just switched from Mongoid (MongoDB) to NoBrainer (RethinkDB) for a new project.

The migration was mostly painless. But I have found an intermitent error that says something along the lines:

    rake test
    Run options: --seed 23337
    
    # Running:
    
    *****E***
    
    Fabulous run in 0.366772s, 24.5384 runs/s, 40.8973 assertions/s.
    
    1) Error:
      API::RecetasController#test_0001_debe regresar la lista de recetas:
    SystemStackError: stack level too deep
    app/controllers/api/recetas_controller.rb:4:in `index'
        test/controllers/api/recetas_controller_test.rb:11:in `block (2 levels) in <top (required)>'
    
    9 runs, 15 assertions, 0 failures, 1 errors, 0 skips

The code in question is this: 

```ruby
class API::RecetasController < ApplicationController
  def index
    @recetas = Receta.all
    respond_with( @recetas )
  end
  ...
end
```

I'm kind of new to the NoSQL party, maybe I'm doing it wrong or something, but I figured I could ask here for pointers. What's surprising to me is that sometimes the test runs without problem, and sometimes it breaks.

If I do a `rake nobrainer:reset` it stops breaking. Then what's the error about?
I have found that it happens sometimes when `Receta.all.to_json` is called.

I guess the right way to do it is with `Receta.all.to_a` before a `.to_json` is called?

Do you have any advice on this? Or could you shed some light on why is this happening?

**Comment by ajselvig** [comment]
Try Receta.all.entries

**Comment by lobo-tuerto** [comment]
Excellent, thank you very much!

**Comment by nviennot** [comment]
Seems fishy to me. If you could share your terminal with me so I can inspect closer, that's be great.

You can use http://tmate.io/ -- email me your ssh conection
