### ISSUE TITLE
[Question] Coupund index returns nothing

### ISSUE THREAD

**Issue by zedtux** [nviennot/nobrainer#135]
Given the following model:

```ruby
class Post
  include NoBrainer::Document

  field :category_id, type: Fixnum, required: true
  field :active, type: Boolean, default: true

  index :active_posts_compound, [:category_id, :active], multi: true
end
```

and the following call:

    Post.where(:active_posts_compound.any => [category_id, true]).to_a

but the following output:

    []

The generated ReQL (built based on the NoBrainer log) is the following:

```javascript
r.db('example_development')
  .table("posts")
  .getAll([1, true], {"index": "active_posts_compound"})
  .coerceTo("array")
  .distinct()
  .orderBy(r.asc("id"))
```

A working ReQL is the following (notice that I have removed the `[]` in `getAll()`:

```javascript
r.db('example_development')
  .table("posts")
  .getAll(1, true, {"index": "active_posts_compound"})
  .coerceTo("array")
  .distinct()
  .orderBy(r.asc("id"))
```

and the output is the expected documents.

Obviously I can't remove the `[]` in my Ruby code when calling `where` with the index so I'm wondering how should I write the `where` call so that it do not add the `[]` in the query ?
(Or is NoBrainer which is logging with `[]` while the query in RethinkDB is without ?)

**Comment by nviennot** [comment]
You shouldn't use multi in your case. Declare your compound index as such:

```ruby
class Post
  index :active_posts_compound, [:category_id, :active]
end
```

To query it, you actually use a regular query:

```ruby
Post.where(:category_id => 1, :active => true).count
```

NoBrainer uses the compound index automatically as it generates the following query:
```ruby
r.table("posts").get_all([1, true], {"index" => :active_posts_compound}).count
```

**Comment by zedtux** [comment]
Thank you !

Then I've misunderstood the `:multi` flag. What is it for ?

**Comment by nviennot** [comment]
Things like this:

```ruby
class Post
  field :tags, :index => :multi
end

Post.create(:tags => ['sunday', 'morning', 'sunny'])
Post.where(:tags.any => 'morning') # matches the created post.
```

**Comment by zedtux** [comment]
Got it ! Thank you again.

**Comment by nviennot** [comment]
Pas de soucis :)
