### ISSUE TITLE
save() behavior proposal

### ISSUE THREAD

**Issue by nviennot** [nviennot/nobrainer#141]
I'm making this issue to plan for the removal of `save()`. I've been looking at open source projects using nobrainer, and it seems that people do not realize that `save()` does not return a boolean.

To make this non ambiguous, I think we should only have `save?` and `save!`.
However, for compatibility purposes, a configuration flag `config.save_behavior` would be available to the user so he can specify what nobrainer should do when receiving a `save()` call.
This configuration flag could be set to `:raise`, `:save?`, or `:save!` depending on what the user wants. The default would be `:raise`.

**Comment by ajselvig** [comment]
Would you make the same behavior for create and update, then?

**Comment by nviennot** [comment]
For `update`, yes.

For `create`, I'm not sure. Not returning the created instance is weird, so there's not going to be a `create?()`. Keeping `create()` is probably fine. renaming `create()` for `create!()` is probably not that useful.

**Comment by ajselvig** [comment]
> renaming create() for create!() is probably not that useful.

How is that any different than renaming save() to save!() ?

**Comment by nviennot** [comment]
I've seen too many bugs go unnoticed because a developer used save() without checking the returned value. create() on the other hand always raises in case of an error.
At the end of the day, I just want an API that reduces the number of bugs one may have.
