### ISSUE TITLE
NoBrainer.sync_indexes doesn't update indexes in all databases (multitenant design)

### ISSUE THREAD

**Issue by grzesiek** [nviennot/nobrainer#143]
Hi

I think that `NoBrainer.sync_indexes` should synchronize indexes in all database when using multi-tenant design. Or at least it should provide some optional configuration like `NoBrainer.sync_indexes(all_databases: true)`.

I think this would be logical and consistent behavior.  What do you think ?

Best regards,
 Grzegorz

**Comment by grzesiek** [comment]
This also doesn't work:

```ruby
NoBrainer.db_list.each do |db|
  NoBrainer.with_database(db) { NoBrainer.sync_indexes }
end
```

neither do

```ruby
NoBrainer.db_list.each do |db|
  NoBrainer.with_database(db) { NoBrainer.update_indexes }
end
```

what is suggested in documentation here: http://nobrainer.io/docs/multi_tenancy/ (`update_indexes` method does not exist in context of `NoBrainer` module)

**Comment by grzesiek** [comment]
It seems I need to investigate this more thoroughly. I'm just letting you know that there may be some confusion in NoBrainer behavior with multi-tenant design.

**Comment by nviennot** [comment]
So the problem with `NoBrainer.sync_indexes(all_databases: true)` is that NoBrainer doesn't know the list of DBs you want to sync apriori. Going through the list of DBs might not be useful as you might have some test db and all.

However, it seems that you could benefit from a shortcut like `NoBrainer.with_each_database { }` that does what you do with `db_list` and `with_database`.

I'm a little confused why seems to work, only if you have all models loaded:  `NoBrainer.sync_indexes` calls [`NoBrainer::Document::Index::Synchronizer.sync_indexes`](https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/document/index/synchronizer.rb#L66) which calls [`new(NoBrainer::Document.all)`](https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/document/index/synchronizer.rb#L63) which then call [`Rails.application.eager_load!`](https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/document/core.rb#L8) which should load all the models.

I've fixed the documentation regarding `update_indexes`

**Comment by grzesiek** [comment]
I'm not using it with Rails (it is plain rack application). I'm using `autoload` strategy so `NoBrainer::Document.all` will return documents list only after `requiring` documents explicitly.

I'll let you know if I find something that may lead to improving NoBrainer :)

Cheers,
 Grzegorz

**Comment by nviennot** [comment]
I see, I've added a clarification in the docs regarding your models :)

cheers
