### ISSUE TITLE
Model.where(:id.in => []) should behave consistent with ActiveRecord's Model.find([]) 

### ISSUE THREAD

**Issue by HendrikW** [nviennot/nobrainer#144]
`Model.where(:id.in => [])` raises a `RethinkDB::RqlCompileError` with `r.table("models").get_all({"index" => :id}).order_by(r.asc(:id))` missing an argument.

It should simply return `[]`.

**Comment by HendrikW** [comment]
awesome. thanks a lot

**Comment by nviennot** [comment]
you're welcome :)
