### ISSUE TITLE
find_by does not behave like ActiveRecord

### ISSUE THREAD

**Issue by esbeka** [nviennot/nobrainer#145]
In ActiveRecord, the `find_by` method will try to look-up the model, but returns `nil` when not found.
If you want it to raise exceptions, you should use `find_by!` instead.
See: [RoR Guide on Active Record Querying](http://guides.rubyonrails.org/active_record_querying.html#find-by)

However, in NoBrainer, the `find_by` raises exceptions in case the model was not found.
I believe that the default behaviour of `find_by` should be changed to ActiveRecord style, such that most gems and other projects do not require specific find implementations to support NoBrainer.

Current implementation: [lib/no_brainer/criteria/find.rb - find_by method](https://github.com/nviennot/nobrainer/blob/8a88a4f0c923297829d217552b5c80479a097b15/lib/no_brainer/criteria/find.rb#L9)

**Comment by nviennot** [comment]
well, right now we have the nice parallelism where `find(id)` is `find_by(:id => id)` and `find?` uses `find_by?`.
If `find` raises, and `find_by` does not, I'd think it would be confusing. I'd rather remove the `find_by` implementation at this point if it creates issues.

**Comment by esbeka** [comment]
I agree that the functionality in ActiveRecord is not what you would expect, I afraid they will not change this any time soon.
Removing `find_by` would break the compatibility with ActiveRecord even more.

**Comment by nviennot** [comment]
I think it's okay to replace `find_by(xxx)` with `where(...).first` (it's just 4 more characters).
Removing `find_by` is won't be creating unexpected bugs in production. Changing the semantics would.

If some library really needs it, we'll see about reintroducing it. Meanwhile, I see no reason to keep it.
