### ISSUE TITLE
before_create no more called since version 0.24

### ISSUE THREAD

**Issue by zedtux** [nviennot/nobrainer#146]
Given the following model:

```ruby
class User

  field :creation_date, type: Date, required: true

  before_create :set_creation_date

  ...

  private

  def set_creation_date
    self.creation_date = Time.zone.today
  end
end
```

With the version 0.23 the callback is triggered and the record created while with the version 0.24 it is not and the validation on the `:creation_date` fails

**Comment by nviennot** [comment]
Use a `:before_validation, :set_creation_date, :on => :create` instead of a `before_create`.

This is to match ActiveRecord behavior. More thoughts on it on https://github.com/nviennot/nobrainer/issues/142

**Comment by nviennot** [comment]
I am very sorry for having changed the semantics as it makes you work more :(

**Comment by zedtux** [comment]
Sorry but ActiveRecord has [`before_create`](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html). I don't really agree on this change as I'm pretty sure new comers will be confused.

**Comment by nviennot** [comment]
As you can see here: http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html

ActiveRecord performs validations before calling the before_create callback, and so your code would also fail in ActiveRecord, because the `creation_date` is still `nil` at the time of the validation.

**Comment by nviennot** [comment]
And so the change was in NoBrainer was do to the validations *before* calling `before_create` as opposed to after. The documentation: http://nobrainer.io/docs/callbacks/#orders_of_callbacks is up to date with the new behavior and matches ActiveRecord's

**Comment by zedtux** [comment]
Oh, sorry I haven't see that when looking at the doc ... I was too fast, thank you.

**Comment by nviennot** [comment]
I know people don't read the docs, I won't blame you for that.
It's my bad. Changing semantics is really not an easy thing to deal with.
