### ISSUE TITLE
[HowTo] Retrieve the newer document with the lower value ?

### ISSUE THREAD

**Issue by zedtux** [nviennot/nobrainer#147]
Given the following model:

```ruby
class User
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :friends_count, type: Fixnum, required: true

  ...
end
```

I would like to retrieve the `User` created the sooner:

 - with the higher amount of friends
 - with the lower amount of friends

I did the first point using `max` (with a block to pass the 2 fields `:friends_count` and `:created_at`).
Now for the second point, using `min` is giving me the older with the less friends but I want the newer.

What is the best way to achieve this ? Is there a nice method to do this or do I have to build a `where` ?

**Comment by nviennot** [comment]
I wasn't sure what you meant, is this what you mean? :

```ruby
User.create(:id => '1', :created_at => 8.days.ago, :friends_count => 1)
User.create(:id => '2', :created_at => 7.days.ago, :friends_count => 1)
User.create(:id => '3', :created_at => 6.days.ago, :friends_count => 2)
User.create(:id => '4', :created_at => 5.days.ago, :friends_count => 2)
User.create(:id => '5', :created_at => 4.days.ago, :friends_count => 2)
User.create(:id => '6', :created_at => 3.days.ago, :friends_count => 2)
User.create(:id => '7', :created_at => 2.days.ago, :friends_count => 1)
User.create(:id => '8', :created_at => 1.days.ago, :friends_count => 1)

User.order_by(:friends_count => :desc, :created_at => :asc).first.id # returns '3'
User.order_by(:friends_count => :asc,  :created_at => :asc).first.id # returns '1'
```

**Comment by zedtux** [comment]
Yeah, exactly that ! Thank you :)

I haven't though about `order_by`, cool.

**Comment by nviennot** [comment]
btw, min/max are implemented with order_by: https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/criteria/aggregate.rb#L4-L10

**Comment by zedtux** [comment]
OK. My first try was `.min(:friends_count).max(created_at)` but as you're using `first` it's giving an object. Now I don't really know if chaining `min` and `max` would make sense ...

**Comment by nviennot** [comment]
chaining `min` and `max` does not make sense as they return an object :)

**Comment by zedtux** [comment]
I was wondering on the theory of chaining them (I know they are giving an object).
