### ISSUE TITLE
cannot access field in nobrainer

### ISSUE THREAD

**Issue by 34code** [nviennot/nobrainer#148]
gemfile

```rethinkdb (>= 2.0.0.0)```
```nobrainer (0.25.1)```

I have a field called activated in User.rb model.

```field :activated```

and the following code:

```ruby
def User.activated?
  self.activated
end
```

Yet I get the following error:

```undefined method `activated' for User:Class```

**Comment by nviennot** [comment]
Remove the `User.` in your code, otherwise, you are making a class method, not an instance method.

**Comment by nviennot** [comment]
and also, if you declare the field as `:type => Boolean`, this method will be automatically provided.

**Comment by 34code** [comment]
If I remove ```User.``` , my controller throws an error: 

```undefined method `activated?' for #<NoBrainer::Criteria:0x007f9364661148>```

btw thanks for the super fast reply :)

**Comment by nviennot** [comment]
ohh so you are looking to make a named scope then.

```ruby
class User
  scope :activated { where(:activated => true) }
end
```

**Comment by 34code** [comment]
Not sure about this scope thing. That particular line gives me a syntax error in User.rb..

Everything was working great earlier and ```find_by``` was not deprecated and ```has_secure_password``` was working out of the box..

Now the new version released and it seems some things have broken. I would love to help more by debugging if I can. Is that scope line supposed to go in controller and not model as I assumed perhaps?

**Comment by nviennot** [comment]
Install http://tmate.io/ and share your terminal with me (send me the connection link via email)

**Comment by 34code** [comment]
excellent! thanks :)
