### ISSUE TITLE
ActiveRecord Touch

### ISSUE THREAD

**Issue by VidhyaKumar** [nviennot/nobrainer#150]
Can you please implement the touch method to update the timestamps in RethinkDB, thank you.

**Comment by kuldeepaggarwal** [comment]
@nviennot: Are we not considering the timezone here?

**Comment by nviennot** [comment]
`touch()` has the same behavior as timestamps with created_at and updated_at, they just use `Time.now`. The configuration of NoBrainer dictates what timezone behavior should be applied when serializing to the DB.

**Comment by kuldeepaggarwal** [comment]
Thanks for the explanantion :yellow_heart:
