### ISSUE TITLE
`Pluck` is not consistent with Rails API

### ISSUE THREAD

**Issue by kuldeepaggarwal** [nviennot/nobrainer#152]

**Comment by nviennot** [comment]
Can you provide a more detailed explanation?

**Comment by kuldeepaggarwal** [comment]
In [this](https://github.com/kristianmandrup/feature-config/blob/master/lib/feature_config/storage/rethink_db.rb#L38) line, I need to manually loop over the column and get the array of values and also need to apply `without_ordering` and `raw` clause.

**Comment by nviennot** [comment]
I see. the API is consistent with http://rethinkdb.com/api/ruby/pluck/ and
http://rethinkdb.com/api/ruby/without/

So the API is consistent with the RethinkDB API, and not with ActiveRecord. I'm not sure going away from the RethinkDB API is a good choice. I'd rather provide an option to `pluck()` to provide the behavior you need. Any suggestions?

**Comment by kuldeepaggarwal** [comment]
But then I should not need to use `without_ordering` clause.

**Comment by nviennot** [comment]
Adding `without_ordering` is not necessary. The default ordering is only there to provide a deterministic response.

**Comment by nviennot** [comment]
So you have two ways to achieve what you want:

1. With objects. Here, `name` is called on each returned object, giving you the ability to go through user defined getters.

```ruby
def names
  pluck(:id, :name).map(&:name)
end
```

1. With RQL. All the work is done by the DB:
```ruby
def names
  NoBrainer.run { rql_table.map { |doc| doc['name'] } }
end
```

**Comment by kuldeepaggarwal** [comment]
Why ordering is there in every query?

**Comment by nviennot** [comment]
So results are deterministic. Further details at http://nobrainer.io/docs/fields/#primary_key
