### ISSUE TITLE
Feature specs with capybara fail due to auto table creation error

### ISSUE THREAD

**Issue by vidkun** [nviennot/nobrainer#154]
I'm migrating a small app from mongodb over to rethinkdb and having issues with my feature specs using capybara. 

A few of them keep failing with an error about auto table creation failing because it can't find the model. Here is a snippet of the results:
```
  2) Forgotten password resets a password when following the email link
     Failure/Error: let!(:user) { create(:user, :valid_password) }
     RuntimeError:
       Auto table creation is not working for `autotrakr_test.users` -- Can't find the corresponding model.
     # ./spec/features/users/forgot_password_spec.rb:4:in `block (2 levels) in <top (required)>'

  3) Signing up allows a user to sign up for the site and creates a user in database
     Failure/Error: expect(User.count).to eq(0)
     RuntimeError:
       Auto table creation is not working for `autotrakr_test.users` -- Can't find the corresponding model.
     # ./spec/features/users/registration_spec.rb:5:in `block (2 levels) in <top (required)>'
```

Unit tests against the User model and users controller work just fine when running one of the spec files individually such as `bundle exec rspec spec/models/user_spec.rb`. However, if I try running the whole test suite with `bundle exec rspec` I get failures for nearly everything with these errors about auto table creation.

I haven't been able to find any documentation on auto table creation either.

Is there some sort of connection delay that is being overloaded by specs running too quickly or is there a particular way that rails_helper.rb should be setup for cleaning the db during tests? the Rspec.configure block currently has:
```
config.before(:all) do
    NoBrainer.drop!
    NoBrainer.sync_schema
  end

  config.before(:each) do
    NoBrainer.purge!
    NoBrainer::Loader.cleanup
  end
```

Thanks.

**Comment by nviennot** [comment]
Don't put `NoBrainer::Loader.cleanup`

**Comment by vidkun** [comment]
That fixed her right up! Thanks!

What exactly does that line do? I pulled that config from a modified version of your spec_helper for this gem. 

There doesn't seem to be any info around for how to set things up for testing an using nobrainer with rspec (or any test suite for that matter).

**Comment by nviennot** [comment]
`NoBrainer::Loader.cleanup` is used internally to clean class caches for when reloading models (e.g. typing `reload!` in your console), and so NoBrainer would be unable to locate your models if the model ode is not loaded again.

I'm not sure why you put that there initially (I couldn't find this in the docs).

Also, I'm not sure why you would put `NoBrainer.drop!`, it might make your test suite slower to boot.

I've put a bit of documentation here: http://nobrainer.io/docs/management/#when_running_tests -- But the documentation should be clarified: testing deserves its own section.

**Comment by vidkun** [comment]
I agree it deserves it own section. Maybe if I get this all figured out more I can help contribute some more docs on it. This is only my third day with rethinkdb.

Again, that entire config was ripped straight out of your spec_helper for this gem and cleaned up references to the conf section you had defined in there as well.

The `NoBrainer.drop!` was in order to clean out the test db before each run of the test suite to ensure no conflicts with pre-existing test data. Sort of in the same thought as using DatabaseCleaner gem with other ORMs. Is it not necessary?

On another note, I'm also seeing odd results with where() queries. Would you prefer I open a separate issue for those?

**Comment by nviennot** [comment]
If you do contribute on the docs, that would be fantastic! It definitely needs some help! :heart: 

With `.purge!` alone, you should not get any conflict with pre-existing data.

`drop!` is useful in NoBrainer test suite because some Models change primary key settings and other weird things like that (once a primary key name is changed, it cannot be changed anymore, the table must be deleted, which sync_schema does not do). If your test is green without `drop!`, take it out, it will be slightly faster to not re-create the tables every time.

From what I see on the DatabaseCleaner docs, they only operate on the `before(:each)` blocks. NoBrainer has `.purge!` to truncate tables, so that's pretty much equivalent. I would not recommend pulling in an extra gem dependency like DatabaseCleaner just to invoke `purge!`.

Yes, please create a separate issue for the where() stuff.
