### ISSUE TITLE
Odd results with where() queries

### ISSUE THREAD

**Issue by vidkun** [nviennot/nobrainer#155]
I keep getting strange or inconsistent results with where() queries. I believe they stem from nobrainer returning a record or instance of Model if a result is returned, but returning a NoBrainer::Criteria (which is not nil) if no results are found. This is causing all sorts of issues with my specs for my sessions and password_reset controllers. I imagine it's going to end up biting me in the rear in the actual application as well.

I've tried many different combinations of adding .first on the end of the where() query, changing the following `if user` conditionals to `if user.present?`, changing the `user.whatever_method` calls to `user.first.whatever_method` calls, etc. It seems like I get part of it working and passing, but it breaks a different part for a similar reason and I have to change that part to something different, and then circle back around over and over.

current code can be found at https://github.com/vidkun/autotrakr/tree/rethinkdb_migration. Files of interest at this point are the feature specs, the sessions_controller, and the password_resets_controller.

Thanks.

**Comment by ajselvig** [comment]
Not sure where the confusion is here. NoBrainer will always return a
criteria (which is not nil, as you said) from where(), regardless if
there's zero, one, or many results.

.first will return the first result if there is one, or nil.

If you want an array of the results, you can use .entries.

**Comment by vidkun** [comment]
That was my original thought and understanding of how it should work. However, for example, if I change line 6 in the password_resets_controller.rb create action to be 
`user = User.where(email: params[:email]).first`
then run my specs/controllers/password_resets_controller_specs.rb against it, I get a number of errors such as:
```
1) PasswordResetsController POST create with a valid user and email finds the user
     Failure/Error: post :create, email: user.email
     NoMethodError:
       undefined method `first' for #<User:0x007ff4d7a286d0>
     # ./app/controllers/password_resets_controller.rb:6:in `create'
     # ./spec/controllers/password_resets_controller_spec.rb:17:in `block (4 levels) in <top (required)>'
```
where NoBrainer is returning an actual instance of User instead of a criteria/array and therefore doesn't respond to .first.

However, all of the specs related to the edit action pass just fine with a similar statement on line 18:
`@user = User.where(password_reset_token: params[:id]).first`

Removing .first from the end to match line 6 above will cause it to fail because it is being returned a criteria/array instead of a User instance.

So what am I missing?

**Comment by nviennot** [comment]
On the following line: https://github.com/vidkun/autotrakr/blob/rethinkdb_migration/spec/controllers/password_resets_controller_spec.rb#L14
The return value of `where` is mocked to return `user`, so NoBrainer is not even invoked. As a piece of advice, avoid using mocks, it decreases trendemously the value of your tests, especially when mocking external libraries, because if the library API changes for whatever reason, your test will still pass. Don't test an echo chamber.

**Comment by vidkun** [comment]
Nice catch and thanks for the help.

For the reference of anyone else that finds themselves in a similar situation, I was able to fix the failing spec with some creative mocking shown here: https://github.com/vidkun/autotrakr/blob/rethinkdb_migration/spec/controllers/sessions_controller_spec.rb#L33

**Comment by nviennot** [comment]
Perhaps my earlier comment wasn't clear.
You should NOT mock NoBrainer's API in your integration tests.

**Comment by nviennot** [comment]
Try this: `expect_any_instance_of(User).to receive(:authenticate)`

Or better, test that you are getting a 200 back from your controller when the credentials are correct, and some 403 or something when they are incorrect.

**Comment by vidkun** [comment]
No, your comment was clear and made sense. I just get to work on this in very small and occasionally rare bursts of time so I was trying to make the specs work and such until I could spend the time to think through how I wanted to rework that section with your comment in mind.

After giving it some thought, those two specs aren't really necessary. The others in that context cover it pretty well. And most options for testing them involve switching that piece of the sessions controller to use instance variables instead of local ones which I don't want to do. So, I just removed those two.

Thanks again, though.

**Comment by nviennot** [comment]
Okay :)
Let me know if you encounter other issues or if you have suggestions :)
Thank you :)
