### ISSUE TITLE
Conditional shortcut for required validation

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#157]
This isn't a bug, really, but it would be nice to be able to specify an inline conditional for the required validation. Essentially, to be able to replace:

```ruby
belongs_to :bar
validates :bar, presence: true, if: -> {self.some_method}
```

with

```ruby
belongs_to :bar, required: -> {self.some_method}
```

It's a minor difference, just thought I'd bring it up.

**Comment by nviennot** [comment]
You can if you pass options, they are passed to the validator:

```ruby
belongs_to :bar, required: ->  {if: :some_method}
```

**Comment by ajselvig** [comment]
Gotcha, thanks. Maybe worth noting in the docs?
