### ISSUE TITLE
Allow string keys for where attribute keys

### ISSUE THREAD

**Issue by robertjpayne** [nviennot/nobrainer#158]
I'm not sure the best way to go about this, but I'm attempting to *not* use fat arrows but NoBrainer's query syntax sometimes requires them:

Works: `.where(:id.in => ['1']`
Doesn't Works: `.where('id.in': ['1'])`

Would it be a overly hard to allow such a change? I know it'd involve detecting string keys and converting them to symbols first.

I may attempt a PR :)

**Comment by robertjpayne** [comment]
Also totally understand if this is not plausible, I just had a dig through the code and it looks like it may be difficult to allow such a thing.

**Comment by nviennot** [comment]
You can do this: `.where(id.in ['1'])` (omit the `:`).

**Comment by nviennot** [comment]
You can also do `.where(:id.in(['1']))` (with parenthesis)

**Comment by robertjpayne** [comment]
Perfect, thanks!
