### ISSUE TITLE
nobrainer might break activerecord migration generators

### ISSUE THREAD

**Issue by modosc** [nviennot/nobrainer#165]
we're using ```nobrainer``` alongside ```activerecord```. i noticed today that i can't generate a new ```activerecord``` migration:

    $ rails g migration foo
      error  nobrainer [not found]

this works however:

    $ rails g active_record:migration foo
      create  db/migrate/20150925205127_foo.rb

after a quick glance i can't see anything in the ```nobrainer``` code that seems a likely culprit but maybe you've got a better idea?

**Comment by nviennot** [comment]
NoBrainer has no support for migration at the moment.
Feel free to make your own scripts :)

Let me know if you need some more guidance

**Comment by modosc** [comment]
for now i just want the original behavior - is there a specific nobrainer rake task i can disable to get back to that?

**Comment by nviennot** [comment]
I can do `rails g active_record:migration` and it works along side with NoBrainer

**Comment by modosc** [comment]
sorry, i'm not being clear - that does work but before i added ```nobrainer``` i could also to ```rails g migration``` and it would magically run ```rails g activerecord:migration``` - i want that behavior back and i can't figure out which part of the nobrainer rake tasks would be affecting that. thanks!

**Comment by nviennot** [comment]
You might want to fiddle with https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/railtie.rb#L4
Perhaps it's configurable directly from config files.

**Comment by modosc** [comment]
yep, that's it. i wonder if that could selectively gate on ```config.warn_on_active_record```? that probably would be unclear though - for now i'll just manually set ```config.app_generators.orm :active_record``` in ```application.rb```. thanks!
