### ISSUE TITLE
Join with optional belongs_to

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#173]
The documentation says that .join() performs an inner join, but I'm getting an error whenever I try to join on an association that is optional (i.e. there are records that don't have the association id):

```ruby
class Foo
  include NoBrainer::Document
end

class Bar
  include NoBrainer::Document
  belongs_to :foo
end

Bar.create!
Bar.join('foo').entries
```

prints:

```
No attribute `foo_id` in object: (RethinkDB::RqlRuntimeError) ...
```

Is there any way around this?

**Comment by nviennot** [comment]
That problem was fixed already, update nobrainer :)
I pushed a quick fix, unrelated to your problem thought.

**Comment by ajselvig** [comment]
Yup, works great. Thanks.

I thought I had a very recent version, but apparently it was several months old...
