### ISSUE TITLE
conflict with active_record

### ISSUE THREAD

**Issue by MadBomber** [nviennot/nobrainer#177]
```ruby
require 'active_record'
require 'nobrainer'
puts "boom!"
```
The order of the requires does not matter.  Whichever gem is 2nd results in a load error:
```bash
/Users/dvanhoozer/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- nobrainer (LoadError)

$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ gem --version
2.5.0
$ gem list nobrainer activerecord
nobrainer (0.30.0)
activerecord (4.2.5, 3.2.22)
```

**Comment by nviennot** [comment]
I can't reproduce the issue.
Please install http://tmate.io/ and share your terminal with me (you can use email to send the connection string) thanks!

**Comment by MadBomber** [comment]
It also could not reproduce the issue on my fedora FC20 box with ruby 2.2.2 ... gotta be something wrong with my Mac's environment.  Will investigate more today.

**Comment by MadBomber** [comment]
Its looking like a ruby 2.2.3 problem.  I did:
```bash
rvm use 2.2.2
gem up
gem clean
# run test program; it worked fine
rvm use 2.2.3
gem up
gem clean
# run test program; it abended with the failure to load
```
When you attempted to reproduce were you also using ruby 2.2.3 ?

**Comment by MadBomber** [comment]
I blew 2.2.3 away then reinstalled it via latest version of rvm.  Installed activerecord and nobrainer.  Ran test program.  Every thing is working fine.  Please mark the issue as closed.
