### ISSUE TITLE
Model.insert_all and generated keys

### ISSUE THREAD

**Issue by alolis** [nviennot/nobrainer#179]
Hello,

I am using latest version of nobrainer gem with RethinkDB 2.1.4 and suddenly when I execute model.insert_all I do not get the returned keys that were generated. I debugged nobrainer a little bit and it seems that the problem is here:

````
NoBrainer::Document::Persistance line 144
````

````ruby
 def insert_all(*args)
      docs = args.shift
      docs = [docs] unless docs.is_a?(Array)
      docs = docs.map { |doc| persistable_attributes(doc) }
      result = NoBrainer.run(rql_table.insert(docs, *args))
      result['generated_keys'].to_a
  end
````

`result` hash does not have a `generated_keys` key; it only contains `deleted`, `errors`, `inserted`, `replaced`, `skipped` and `unchanged`

Any ideas where the `generated_keys` field went?

**Comment by nviennot** [comment]
Can you provide a standalone working example that exhibit the bug?
Thank you :)

**Comment by alolis** [comment]
@nviennot , It seems that I will answer my own question. The reason that `generated_keys` is missing is because I append custom IDs to those documents. I tested without appending custom IDs and it seems to be working fine.

Model.insert_all however, will return the `generated_keys` field, which in my case does not exist and as a result is hard for me to implement error handling. In my case the `inserted` field is more appropriate. Is there a way to get the whole `result` or `insert_all` must be changed?

**Comment by nvedul2** [comment]
@nviennot hi nicholas good morning....i have a question regarding playdrone project.There is json link 
( https://archive.org/download/playdrone-snapshots/2014-10-31.json) in the page
https://archive.org/details/android_apps&tab=about . But the playdone app you have designed is used to download apps. How can i get the json file of all the apps in market on a particular day ? I have implemented playdrone ,So how how do i get the application id(or json for that matter) of all the apps in google play on a particular day ? please help only on this one. I am in tight situation....thank you so much

**Comment by nviennot** [comment]
You might want to use raw RQL. You may do something like this:

```ruby
NoBrainer.run { Model.rql_table.insert(documents) }
```

**Comment by nvedul2** [comment]
@nviennot hi nicholas regarding playdrone..how did you generate the json file which has all the app details ? I implemented playdrone to download..but couldnt figure out how to download the apps.

**Comment by nviennot** [comment]
@nvedul2 this is not the place to talk about playdrone. please stop :)

**Comment by nvedul2** [comment]
Ok. Sorry. I was not able to get your attention.
 Out of desperation I had to do.
 Please let me know.
How to get the details json file for all the apps today in google store ?
I have implemented play drone in my local system successfully.
 I have to get the json file for today.How did you get it ?
I will not disturb you. i have a project deadline this weekend. At least
if you could tell me that would be helpful. Plzzzz.

Thanks,
Naga

**Comment by alolis** [comment]
@nviennot , cheers, i will give it a go

@nvedul2  , it's not polite to try to hijack another persons thread.
