### ISSUE TITLE
Using index for attr:defined queries

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#180]
I can't figure out how to use a field's index to query records that have that field defined:

```ruby 
field :foo, index: true
```

Seems like this should use the index, but the query uses a regular filter statement and I get the perf warning:

```ruby
Model.where(:foo.defined => true)
```

Doesn't it seem like this query should be able to be done with getAll on the index?

**Comment by nviennot** [comment]
Yeah, I'm not sure what RQL I should generate to use the index

**Comment by ajselvig** [comment]
I believe it's something like:

```ruby
r.table("models").between( r.minval, r.maxval, {"left_bound" => "open", "index" => "foo"})
```

**Comment by ajselvig** [comment]
(this is 50x faster than the corresponding filter statement for my particular dataset)

**Comment by ajselvig** [comment]
Works perfect, thanks!
