### ISSUE TITLE
Stack level too deep when using atomic operations

### ISSUE THREAD

**Issue by diegocouto** [nviennot/nobrainer#182]
Guys, I'm having some trouble to update atomically a model attribute.

```ruby
class Profile
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :views, type: Integer, default: 0

  def add_view
    self.queue_atomic do
      self.views += 1
    end

    self.save?
  end
```

From a controller, I can't run `@profile.add_view` without getting a `Stack level too deep` error. Instead of encapsulating this action into a instance method, I also tried to to it from the controller and, unfortunately, without success.

**Comment by nviennot** [comment]
I can't reproduce this bug (I tried in a controller).

Can you provide a standalone test case for me to reproduce?
