### ISSUE TITLE
Can't save self-referential belongs_to

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#184]
If I have a Foo model with belongs_to :foo association that references the same model, I cannot save an instance of that model if its foo_id=id (because that foo doesn't exist in the db yet). Is there any way we can skip this validation in this specific case? 

I can provide a complete code example if needed.

**Comment by ajselvig** [comment]
A gentleman and a scholar, as usual. Thanks!

**Comment by nviennot** [comment]
ahah thanks andy :D
