### ISSUE TITLE
sync_schema not working for resource destructions

### ISSUE THREAD

**Issue by ahnbizcad** [nviennot/nobrainer#185]
rake nobrainer:sync_schema works to add tables to the database when running a rails resource generator like `rails g scaffold Article`, but when you then run `rails d scaffold Article` and then `rake nobrainer:sync_schema`, the tables are not destroyed in rethinkdb, when viewed from localhost:8080

**Comment by nviennot** [comment]
NoBrainer will never delete data. We don't want precious data to vanish do we :)

**Comment by ahnbizcad** [comment]
Interesting. how do we know how long or when the join table actually does get deleted?

**Comment by dalanmiller** [comment]
@nviennot Does this mean that just the scaffolding is removed in Rails but nothing in the database?

**Comment by nviennot** [comment]
@ahnbizcad I don't understand the quesiton

@dalanmiller Correct

**Comment by ahnbizcad** [comment]
thanks for the clarification, both of you.
