### ISSUE TITLE
upsert does not work with associations

### ISSUE THREAD

**Issue by niv** [nviennot/nobrainer#186]
Just a small bug report:  I can't get upsert! to work on associations, like so:

```ruby
class Parent; ... end
class MyModel
  include BaseModel
  belongs_to :parent
  field :username, String
  field :data, String, unique: { scope: [:parent_id, :username] }
end

MyModel.upsert! parent: @parent, username: "me", data: "test"
```

It fails on not finding a matching uniqueness validator (because it's looking for :parent_id instead of :parent). As a consequence, if I do

```ruby
MyModel.upsert! parent_id: @parent.id, username: "me", data: "test"
```

it works as expected.

(Note that I had to set the uniq validator on :data to look for :parent_id, too, instead of :shard.)

**Comment by nviennot** [comment]
I've fixed this bug.

I've also added the `:uniq/unique` option on a `belongs_to` declaration

**Comment by niv** [comment]
Tyvm! That was amazingly quick.
