### ISSUE TITLE
RFC: best way to prevent a object from being destroyed

### ISSUE THREAD

**Issue by niv** [nviennot/nobrainer#187]
Hey,

this isn't a bug report! Instead, I'd like to put forth a code snippet to hopefully get some feedback on.

I have the following "soft" associations, not done through has_one/belongs_to, but through a extra label field.

```ruby
class Staged
  field :label, type: String
end
class Lock
  field :label, type: String
end
```

Now, I'd like to prevent a Lock instance from being destroyed if any Staged with the same label exists. Right now, I'm doing this through a before_destroy hook, like so:

```ruby
before_destroy do
  staged = Staged.where(label: self.label).first
  staged and raise HasStagedError.new("Cannot destroy #{self.label}, still locked")
end
```

I looked into dependent: :restrict, but I do not want to add a has_one to either end, because they cannot reference each other through their primary ids (they are added independently through different endpoints/users).

I'm also aware that the example code I gave isn't race-condition free. :)

The way I do it now, through the callback, seems kind of hackish though. Is there a better way to do this that I missed?

Thanks!

**Comment by nviennot** [comment]
I tried the following:

```ruby
class Lock
  include NoBrainer::Document
  field :label, type: String

  has_many :staged, foreign_key: :label, primary_key: :label, dependent: :restrict
end

class Staged
  include NoBrainer::Document
  field :label, type: String

  has_many :locks, foreign_key: :label, primary_key: :label
end
```

Seems to work fine. A bit hackish as well though :)

**Comment by niv** [comment]
Yeah that works. I completely forgot about :foreign_key.  That'll do for now.  Thank you!

**Comment by nviennot** [comment]
cool!!
