### ISSUE TITLE
How-to: Parse ReQL Response

### ISSUE THREAD

**Issue by francocorreasosa** [nviennot/nobrainer#189]
When I got the users by day (see #188). I got something like this
```
[{"group":{"$reql_type$":"TIME","epoch_time":1454803200,"timezone":"+00:00"},"reduction":19}]
```
How can I turn that in something like this? (took from the RethinkDB Dashboard)
```
[{"group": Sun Feb 07 2016 00:00:00 GMT+00:00 ,"reduction": 19}]
```

**Comment by francocorreasosa** [comment]
I solved it myself. I just added `.to_iso8601` to the query.

```
@users_by_day = NoBrainer.run { |r| User.rql_table.group { |u| u['created_at'].date.to_iso8601 }.count }
```

**Comment by nviennot** [comment]
So the rethinkdb driver wasn't doing the unboxing of RQL types when processing a `group_by` result.

I made a PR to address the issue: https://github.com/rethinkdb/rethinkdb/pull/5373

We'll see how it goes :)
