### ISSUE TITLE
Toggle boolean fields

### ISSUE THREAD

**Issue by brazenbraden** [nviennot/nobrainer#193]
Is there a way to simply toggle a boolean field, akin to the active record 'field.toggle' and 'field.toggle!' ?

```ruby
class User
   include NoBrainer::Document
   field :is_deleted, type: Boolean, default: 0
end

User.first.toggle!(:is_deleted)
```

**Comment by nviennot** [comment]
I'd rather not add any methods that persist documents because rethinkdb has no transactions, and so you need to be aware of where you code is persisting documents. Namely, when calling the `save` and `update` methods.

If you want to do it in a quick way, you can do:

```ruby
User.first.tap { |u| u.update(:flag => !u.flag) }
```
