### ISSUE TITLE
Alias 'order_by' with 'order'

### ISSUE THREAD

**Issue by brazenbraden** [nviennot/nobrainer#194]
I am in the process of converting an app from using Postgres to RethinkDB and with active record, you could call Model.order(id: :desc) however with NoBrainer, it must be Model.order_by(id: :desc).

Is it possible to have an alias for order_by so I can call Model.order() instead. Would save a lot of time altering all the order() calls and also make it easier to switch between different ORMs if needed.

**Comment by nviennot** [comment]
Sure thing!
