### ISSUE TITLE
update_all - crashes rethinkdb.

### ISSUE THREAD

**Issue by icesmurf** [nviennot/nobrainer#196]
It appears nobrainer crashes if you try run something along the lines of:

Mode.where(:allocated => false).update_all(:allocated => true)

Oddly, the generated RQL works perfectly fine when using the rethinkdb driver directly.

`worker: 3ARKLUUcK7fQme
E, [2016-03-25T22:10:45.193627 #26697] ERROR -- : [ 110.1ms] r.table("jobs").get_all(false, {"index" => :assigned}).filter {|var_4| var_4[:completed].eq(false)}.order_by(r.asc(:id)).update({"assigned" => true}) -- RethinkDB::RqlDriverError Connection closed by server.
/home/leons/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.2.0.4/lib/shim.rb:82:in `rescue in response_to_native': Connection closed by server. (RethinkDB::RqlDriverError)
Backtrace:
r.table("jobs").get_all(false, {"index" => :assigned}).filter {|var_4|
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  var_4[:completed].eq(false)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
}.order_by(r.asc(:id)).update({"assigned" => true})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.2.0.4/lib/shim.rb:61:in `response_to_native'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.2.0.4/lib/net.rb:551:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/rethinkdb-2.2.0.4/lib/net.rb:341:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/driver.rb:5:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/reconnect.rb:3:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `block in call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `synchronize'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/connection_lock.rb:8:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/write_error.rb:4:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/profiler.rb:4:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/table_on_demand.rb:3:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/database_on_demand.rb:3:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/missing_index.rb:3:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner/run_options.rb:53:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/query_runner.rb:21:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/nobrainer.rb:26:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/criteria/run.rb:16:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/criteria/run.rb:12:in `run'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/criteria/update.rb:19:in `perform_update'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/criteria/update.rb:5:in `update_all'
	from /home/leons/.rvm/gems/ruby-2.3.0/gems/nobrainer-0.31.0/lib/no_brainer/criteria/cache.rb:73:in `block (2 levels) in reload_on'
	from worker_allocate.rb:128:in `<main>'
`

**Comment by nviennot** [comment]
can you give me a stand alone snippet of code that manifests the bug please? I can't reproduce.

**Comment by nviennot** [comment]
ping?

**Comment by icesmurf** [comment]
humm, wondering if it was a db side issue, the problem has gone away after an upgrade. sorry about that.
