### ISSUE TITLE
RethinkDb::ReqlDriver Error

### ISSUE THREAD

**Issue by mhassaan** [nviennot/nobrainer#199]
hi guys I am trying to configure rethinkdb with my rails application along with postgresql . I have followed the procedure mentioned in the documentation of nobrainer but i am getting this error when i try to add a record using rails console . 

> RethinkDB::ReqlDriverError Connection closed by server (776: unexpected token at 'ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
 
Ruby version is 2.2.4 and rethinkdb is 2.3.0. What am i missing ? Your help will be appreciated.

**Comment by nviennot** [comment]
make sure you are using the latest `rethinkdb` gem: run `bundle update rethinkdb`
otherwise, what do you have when running `bundle show | grep rethink` ?

**Comment by mhassaan** [comment]
I tried removing rethinkdb and then installed again. But now when i run rails c to create any record it gives me error like this 

> RethinkDB::ReqlDriverError Error during handshake: #<Errno::ECONNRESET: Connection reset by peer>
`bundle show | grep rethink` gives me this version `rethinkdb (2.3.0.0)`. 

My OSX is 10.10.5 . Is there anything i could do to make this work ?
