### ISSUE TITLE
Support for RethinkDB users

### ISSUE THREAD

**Issue by gsmetal** [nviennot/nobrainer#200]
In RethinkDB 2.3 user accounts and permissions were added (https://www.rethinkdb.com/blog/2.3-release/). It would be great to support this functionality in NoBrainer configuration (including ENV variables and url).

**Comment by nviennot** [comment]
Good idea, I'll get that out of the door by the end of week 👍

**Comment by meenie** [comment]
For anyone that needs to do this before the work is done, you can connect using the `RETHINKDB_URL` env variable by setting it to `rethinkdb://<user>:<password>@<host>:<port>/<db_name>`.

**Comment by nviennot** [comment]
done
