### ISSUE TITLE
Polymorphic virtual attributes

### ISSUE THREAD

**Issue by cadejscroggins** [nviennot/nobrainer#201]
I just got this error message:

> Virtual attributes are limited to the root class `Feed' for the moment.
> Ask on GitHub for polymorphic support.

Let me know if this is a dup of https://github.com/nviennot/nobrainer/issues/51

**Comment by nviennot** [comment]
nah, it's not a dup.

It's a little challenging, because we have to construct a fancy RQL query with branches (e.g. if `_type == SubClass1`, load the following vattributes, if `_type == SubClass2`, ...).
I don't have much time these days, so I'll have to punt for now.
