### ISSUE TITLE
Creating index utilising r.branch

### ISSUE THREAD

**Issue by meenie** [nviennot/nobrainer#203]
I'm trying to create an index where I can utilise `r.branch()`.  In javascript, it looks something like this:
```
r.db('test').table('foo').indexCreate('my_index', (doc) => r.branch(doc('my_field').isEmpty(), null, [doc('first_field'), doc('second_field')]));
```

How would I go about this in NoBrainer?

**Comment by nviennot** [comment]
I replaced the `isEmpty()` by an `eq(nil)`, because that's probably not what you wanted. Here is how to use it:

```ruby
class Model
  include NoBrainer::Document

  field :my_field
  field :first_field
  field :second_field

  index :my_index do |doc|
    RethinkDB::RQL.new.branch(doc[:my_field].eq(nil), nil, [doc[:first_field], doc[:second_field]])
  end
end
```

**Comment by meenie** [comment]
Thanks a ton! I was about to come back and close it off because I came up with this:
```
index :numerical_aggregation, -> (doc){
    doc['numerical'].is_empty.branch(nil, [doc['survey_id'], doc['completed_at']])
  }
```

You can run `r.branch()` directly off a field.  I appreciate the `RethinkDB::RQL.new` line though :).

**Comment by nviennot** [comment]
cool!

**Comment by meenie** [comment]
@nviennot: I just realised that your example above doesn't work.  The `index` method is looking for a lambda in the second argument.

**Comment by nviennot** [comment]
You are correct, I've updated my code example.
I'll make write an implementation to support for this syntax (because why not).

**Comment by meenie** [comment]
Awesome :)
