### ISSUE TITLE
Support eager_load in raw queries?

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#204]
Do you have any thoughts on supporting eager_load in raw queries? It doesn't seem like there's anything fundamentally preventing this, and it would be generally useful to maintain consistent behavior with the object-wrapped functionality.

**Comment by nviennot** [comment]
It would be a lot of effort to make eager load work in raw query due to how the code is written at the moment. However, raw queries work with join(), so maybe that would be an acceptable compromise for now

**Comment by ajselvig** [comment]
Fair enough. Thanks.
