### ISSUE TITLE
nil value breaks indexed, unique fields

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#206]
I'm not sure if this is a regression; it really seems like someone would've run into it before. 

When passing a nil value into an indexed field with a uniqueness constraint, and error gets thrown during validation. 

``` ruby
class Foo
  include NoBrainer::Document
  field :name, type: String, unique: true, index: true
end
Foo.new.valid?
```

```
Keys cannot be NULL. (RethinkDB::ReqlNonExistenceError)
r.table("foos").get_all(nil, {"index" => :name}).count
                        ^^^
```

I guess it's not super clear to me what the correct behavior is (other than not throwing an exception, of course). I think the only time I've done this in practice it's been with `required: true` as well, so it doesn't really matter.

**Comment by CodeMonkeySteve** [comment]
I think this is a limitation of RethinkDB not supporting `null` values in a secondary index.  See https://github.com/rethinkdb/rethinkdb/issues/1032

**Comment by zedtux** [comment]
I agree with you @CodeMonkeySteve since the error class is `RethinkDB::ReqlNonExistenceError` which is not part of this gem but from the [rethinkdb gem](https://github.com/rethinkdb/rethinkdb-ruby/blob/master/lib/exc.rb#L8), so I'm closing this issue.
