### ISSUE TITLE
Enum not documented

### ISSUE THREAD

**Issue by jeroenvisser101** [nviennot/nobrainer#208]
Enum, as introduced [here](https://github.com/nviennot/nobrainer/commit/b81788452cf7ce8b0156355aeefd012aa104988e), isn't documented as far as I can see. I couldn't find the repo/branch for the docs either, but am happy to contribute if you can point me to it.

Awesome work on nobrainer BTW, we're porting from postgres as we speak 👍

**Comment by jeroenvisser101** [comment]
Also, new release would be appreciated (I see this is not in a version yet, hence the missing docs, probably)

**Comment by jeroenvisser101** [comment]
Never mind, I found the documentation (https://github.com/nviennot/nobrainer.io) and will try to do a write-up on the way home.

**Comment by nviennot** [comment]
I've added the Enum docs.
Thank you for the compliments ❤️ 
Will do a release soon :)

**Comment by jeroenvisser101** [comment]
Thanks!
