### ISSUE TITLE
Paperclip Support

### ISSUE THREAD

**Issue by ajselvig** [nviennot/nobrainer#21]
Any objections to adding an optional concern to generate Paperclip fields? It seems like it could be implemented so that it only requires Paperclip if you use the concern. I know this is a rather trivial thing to add to your own code base, it just seems like it would be very useful to have available to everyone.

**Comment by alolis** [comment]
I assume that this never got implemented since I can not find anything

**Comment by sandstrom** [comment]
@alolis No, the issue was closed. But it's certainly possible to use nobrainer together with paperclip, in various ways.

**Comment by alolis** [comment]
@sandstrom , can you please point me to one? or to an example code if you are aware

**Comment by sandstrom** [comment]
@alolis Hard to give specific advice, paperclip is a pretty broad gem with a bunch of functionality.

But generally, I'd store blobs in a suitable storage (e.g. S3) and only keep the metadata + references in an 'ordinary' database.

**Comment by alolis** [comment]
@sandstrom , thank you for your answers
