### ISSUE TITLE
Strong params, curl and Rails 5 API

### ISSUE THREAD

**Issue by ralphking** [nviennot/nobrainer#211]
Hi,

I'm falling foul of the assign_params method, here: https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/document/attributes.rb#L73

Using Rails 5 RC1. 

Model:

```
class Venue
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :name, :type => String
  field :desc, :type => Text
end
```

Controller:

```
  # POST /venues
  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      render json: @venue, status: :created, location: @venue
    else
      render json: @venue.errors, status: :unprocessable_entity
    end
  end

def venue_params
      params.require(:venue).permit(:name, :desc)
end
```

All very standard. When using curl to test the api, I'm hitting the error inside assign_attributes. I have the attributes in the controller, whitelisted.

`curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"venue":{"name":"test","desc":"something"}}'  http://localhost:3000/venues`

It works fine if I pass them as a hash, which is what the error is checking for:

`@venue = Venue.new(name: params[:name], desc: params[:desc])`

I assume it's doing this because it thinks I'm trying to submit attributes that are not whitelisted. Is this a bug?

Thanks

**Comment by jeroenvisser101** [comment]
@ralphking I had the same thing, and am happy to add [my patch](https://github.com/jeroenvisser101/nobrainer/blob/d99c88f03e2b2a74c01b960e780773a00bfd2d5c/lib/no_brainer/document/attributes.rb#L73-L75) back to master.

**Comment by ralphking** [comment]
Hmm I was thinking of doing the same - just saw in the Docs that nobrainer should play nicely with Rails 5 so wasn't sure if it was a bug or not

**Comment by jeroenvisser101** [comment]
I think it's unexpected, I'll file a PR now.

**Comment by ralphking** [comment]
Ok I'll just borrow your fork for now while I test.

Thanks

**Comment by jeroenvisser101** [comment]
@ralphking there's some other things inside `rails5` branch related to code reloading that are definitely not production-ready yet, so there be dragons there.

**Comment by jeroenvisser101** [comment]
@ralphking I've created a new branch that you can check. The implementation is a little different (it's now really backwards compatible).

**Comment by nviennot** [comment]
@ralphking, I've pushed @jeroenvisser101 fix on master. Does it fixes your issue?

**Comment by jeroenvisser101** [comment]
@nviennot thanks for merging :)
