### ISSUE TITLE
Documentation without Rails

### ISSUE THREAD

**Issue by atomless** [nviennot/nobrainer#215]
Such a shame so much of the documentation outlines Rails based solutions. If I were working with Rails I'd probably use another db and stick with active-record. As an alternative to active record it would be great to have the documentation less geared towards Rails users and more towards vanilla ruby.

**Comment by jeroenvisser101** [comment]
The documentation isn't focused on rails at all, it uses ActiveModel under the hood, and can be used without Rails.

**Comment by jeroenvisser101** [comment]
I think the only thing really focused on rails is http://nobrainer.io/docs/installation/#configuring_nobrainer_with_rails

**Comment by atomless** [comment]
Actually, I take it back. You're right, much of it does not mention rails, just so happened that the first two bits I scanned through were the configuration page (as you mentioned) and at the bottom of this page : http://nobrainer.io/docs/introduction/ 

Which had me worried for a second, whether my ruby/rethink learning curve was going to hit a continual wall of "oh dear but I am not using rails".

Thanks, really enjoying using it with Rethink so far.

**Comment by jeroenvisser101** [comment]
@atomless 👍  some of the ruby ecosystem is really rails-first. I've hit this block too but nobrainer is one of the only libraries that worked easier outside of rails than inside (since inside takes some manual configuration, removing ActiveRecord and getting other gems to work without AR)
