### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by sandstrom** [nviennot/nobrainer#216]
ActiveRecord recently landed a neat feature allowing custom attributes (backed by custom classes) with transparent conversion to/from db values.

Something similar would be very useful in NoBrainer too.

- http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/#yay
- https://github.com/rails/rails/blob/8c752c7ac739d5a86d4136ab1e9d0142c4041e58/activerecord/lib/active_record/attributes.rb

**Comment by jeroenvisser101** [comment]
NoBrainer offers [Custom Types](http://nobrainer.io/docs/types/#custom_types). I think that might be what you're looking for.

**Comment by sandstrom** [comment]
@jeroenvisser101 Thanks! I'm apparently blind.

**Comment by jeroenvisser101** [comment]
@sandstrom you're welcome, glad I could help :)
