### ISSUE TITLE
Is there a way to use outdated reads globally?

### ISSUE THREAD

**Issue by scottrobertson** [nviennot/nobrainer#218]
We have an app that needs to be available when only outdated reads are available. Is there a way to configure NoBrainer to use this for all reads?

**Comment by nviennot** [comment]
You can use a rack middleware or a controller filter wrapped with a `NoBrainer.run_with(:use_outdated => true) { ... }`. Would that be an acceptable solution?

**Comment by nviennot** [comment]
I've added the following option to the configuration file:

```ruby
  # Configures the run options passed to r.run() when executing queries.
  # The options are listed in the RethinkDB run() documentation.
  # The default durability is :soft for development or test environments, otherwise :hard.
  # config.run_options = { :durability => config.default_durability, :read_mode => :single }
```

**Comment by scottrobertson** [comment]
Perfect @nviennot, thank you! Option 1 would not have worked, as it needs to be the entire app, including the devise plugins etc. So this should work very well.
