### ISSUE TITLE
Can not load process_in_background with carrierwave_backgrounder

### ISSUE THREAD

**Issue by dented** [nviennot/nobrainer#221]
Not sure if I should be posting here or on backgrounder, but I can get sidekiq to load up (mostly). However, when trying to add process_in_background or store_in_background. It can't find the method.

I have tried with a brand new 4.2.5.1 and I get the same issue using Gemfile

```
source 'https://rubygems.org'

gem 'rails', '4.2.5.1'

gem 'nobrainer'

gem 'sidekiq'
gem 'sinatra', require: false

gem 'mini_magick', require: false
gem 'carrierwave'
gem 'carrierwave_backgrounder'
gem 'carrierwave-nobrainer'

gem 'active_model_serializers', github: 'rails-api/active_model_serializers'

group :development, :test do
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'thin'
end
```

Not sure what I need to change configurations or if I have to use resque instead.

**Comment by nviennot** [comment]
1) that's a carrierwave issue, not a nobrainer one. please open issues on https://github.com/nviennot/carrierwave-nobrainer next time.
2) remove gem 'carrierwave_backgrounder'
3) next time, include a stack trace in your bug report and more information. try to put yourself in my shoes, and see if I would be able to debug your issue based on the information you gave me.

**Comment by dented** [comment]
That's a good point, I'll post over on https://github.com/nviennot/carrierwave-nobrainer. As for bug trace, I felt it would have helped only if I couldn't recreate with new clean project. I'll include it in the next issue submission.
