### ISSUE TITLE
Fatal Error with spring and user model

### ISSUE THREAD

**Issue by choonggg** [nviennot/nobrainer#225]
Not sure if it's a nobrainer or devise-nobrainer issue.

Gotten fatal error `RuntimeError: Fatal: The model 'User' is already registered and partially loaded.` when using devise-nobrainer. No class methods were declared but fatal error was raised and this is the only model in the app.

The only way to get rid of this is to kill spring and restart the app.

This is how my `User` model looks like
```
class User
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :registerable, :rememberable, :trackable, :omniauthable, omniauth_providers: [:facebook]

  ## Rememberable
  field :remember_created_at, :type => Time
  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
end
```

**Comment by choonggg** [comment]
Sorry, after doing a bit of digging I found this.
https://github.com/nviennot/devise-nobrainer/issues/6
Thanks for the fix, used the master branch for now.
Please close the issue 👍

**Comment by nviennot** [comment]
ah yes, I should release the new gem

**Comment by choonggg** [comment]
Cool, thanks for keeping this gem alive :+1:

**Comment by akaghzi** [comment]
is there any plan to release the new gem?

**Comment by nviennot** [comment]
Done!

**Comment by akaghzi** [comment]
thanks a lot
