### ISSUE TITLE
Enum querying not working?

### ISSUE THREAD

**Issue by choonggg** [nviennot/nobrainer#226]
My enum queries aren't showing any results, am I doing something wrong here?

I even tried using `.where(status: :pending)`
### My model field
```
  field :status, type: Enum, in: [:pending, :complete, :banned], default: :pending

```
### My logs
```
[9] pry(main)> Model.pending.count
[   2.0ms] r.table("models").filter {|var_7| var_7[:status].eq(:pending)}.count -- perf: filtering without using an index
=> 0
[10] pry(main)> Model.first.pending?
[   2.7ms] r.table("models").order_by({"index" => r.asc(:id)}).limit(1)
=> true
[11] pry(main)>
```

**Comment by jeroenvisser101** [comment]
If you added the enum later, it could be that the model you're retrieving doesn't have a status set yet (e.g. status is nil).

**Comment by choonggg** [comment]
Thanks for clearing that up! @jeroenvisser101, that's something I shall take note of, appreciate it.

Closing this issue.
