### ISSUE TITLE
Improve documentation regarding authentication

### ISSUE THREAD

**Issue by steviee** [nviennot/nobrainer#229]
Hi,

IMHO the documentation needs some depth regarding authentication with TLS, different user accounts and environment variables.

Best regards,
Steviee

**Comment by balugege** [comment]
How do you even specify user name and password?

**Comment by nviennot** [comment]
I've pushed a bit of documentation https://github.com/nviennot/nobrainer.io/commit/31fe7b61508a909d0ed618e8c3ea57f255f56cd9
