### ISSUE TITLE
ERROR: Incorrect authorization key

### ISSUE THREAD

**Issue by pbraswell** [nviennot/nobrainer#231]
I'm trying to connect to a Ubuntu 12.04 instance of Rethinkdb, version 2.3.5, deployed in AWS.

I've set up a user and a password and have granted that user access to the RTDB database.  I'm using Rails 5 and in my nobrainer.rb initializer I have:

config.rethinkdb_urls = ["rethinkdb://brian:*******@54.173.46.149:28015/production_nobrainer"]

When I try and access the database, I get "ERROR: Incorrect authorization key"

The Rethinkdb has some information about authorization keys.  I'm not sure how they relate to nobrainer.  I've tried to explicitly set the auth key in the admin console as per the directions: 

r.db('rethinkdb').table('cluster_config').get('auth').update({auth_key: 'newkey'})

But this results in an error: "It's illegal to delete rows from the `rethinkdb.cluster_config` table."

Even if i were to successfully set the access key on the RethinkDB side, I'm not sure how that relates to the nobrainer connection URL.

Any guidance or help would be greatly appreciated!

Peter

**Comment by nviennot** [comment]
try admin as a username?

**Comment by pbraswell** [comment]
By golly, that worked!  Thanks for your help!!
