### ISSUE TITLE
Tracking query times

### ISSUE THREAD

**Issue by scottrobertson** [nviennot/nobrainer#232]
Hey. We use scoutapp.com for monitoring. 

We currently track our non NoBrainer queries, but we need a way to track the queries performed by NoBrainer. What we do for manual queries is wrap it in the following:

```
self.instrument("RethinkDB", RethinkDB::RPP.pp(query)) do
  # call .run
end
```

Can you think of a way to do this globally for all NoBrainer queries? Wrapping each call is not possible (it would be incredibly messy)

**Comment by jeroenvisser101** [comment]
Hey @scottrobertson, we instrument our queries for Appsignal (which is great btw)

I've adapted what we use and that should work for you:

``` ruby
require "nobrainer"

if defined?(ScoutApp) # Adapt to match your module
  class RethinkdDBInstrumentation < NoBrainer::QueryRunner::Middleware
    def call(env)
      self.instrument("RethinkDB", RethinkDB::RPP.pp(env[:query])) do
        @runner.call(env)
      end
    end
  end

  NoBrainer::QueryRunner.stack.insert_after(
    NoBrainer::QueryRunner::Profiler,
    RethinkdDBInstrumentation
  )
end
```

**Comment by scottrobertson** [comment]
@jeroenvisser101 awesome, that is perfect. Thank you! I wasnt aware of `insert_after`

**Comment by scottrobertson** [comment]
> PS. We've been using this, but we're still figuring out how to filter parameters from this (so it wouldn't send data to the monitoring party), do you know if there's any easy way to do that? Preferably without regex magic?

Not yet sadly. The only way I can find is regex at the moment :(

**Comment by jeroenvisser101** [comment]
Ah, too bad, thanks anyways :)

**Comment by nviennot** [comment]
You can get instrumentation by doing:

```ruby
class YourProfiler
  def on_query(env)
    # env is a hash with a bunch of info.
    # see https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/profiler/logger.rb for example usage
  end

  NoBrainer::Profiler.register(self.new)
end
```

**Comment by scottrobertson** [comment]
Nice! Thank you

**Comment by jeroenvisser101** [comment]
@nviennot that one is even better, thanks, will adapt ours too :)
