### ISSUE TITLE
Add belongs_to_many for Array association?

### ISSUE THREAD

**Issue by CodeMonkeySteve** [nviennot/nobrainer#242]
It would be incredibly useful to extend `belongs_to`/`has_many` associations to use arrays of foreign keys, for cases of many-to-many association without the hassle of using a join table.  While there are quite a few DBs that support arrays, I haven't seen any ORM/ODM that support using them for associations.

My proposal is to add a `belongs_to_many` association with the same semantics as `belongs_to` (but with an array type), and modify `has_many` to support it.  

For example, consider a blog post with multiple authors:
```
class Post
  include NoBrainer::Document
  field :author_ids, type: Array
  index :author_ids, multi: true
  # belongs_to_many :authors
  def authors
    @authors ||= Author.where(:id.in => author_ids)
  end
  def authors=(authors)
    @authors = authors || []
    self.author_ids = @authors.map(&:id)
  end
end

class Author
  include NoBrainer::Document
  # has_many :posts
  def posts
    @posts ||= Post.where(:author_ids.any => id)
  end
end
```
This code works as is, but it can't take advantage of caching or eager loading, leading to lots of N+1 queries.  I would think it wouldn't be difficult to add, but I'm not familiar enough with NoBrainer's association internals to attempt it.

**Comment by nviennot** [comment]
Can you show code that exhibits a N+1 queries problem?

**Comment by CodeMonkeySteve** [comment]
Basically, any query where you'd want to eager load the association, e.g.:
```
Post.all.each do |post|    # want: all.eager_load(:authors)
  puts "#{post.title.inspect} by #{post.authors.map(&:name).join(', ')}"
end
```

**Comment by nviennot** [comment]
Making a real association is too complicated for inner arrays. The abstraction might be too leaky. Instead, I propose some sort of eager loading, without using the concept of associations. Here's the code, which can be put after initializing NoBrainer:

```ruby
module NoBrainer
  def self.eager_load_queries(queries)
    if queries.count < 2
      queries.each(&:to_a)
      return
    end

    merged_query = queries.first.dup
    merged_query.options[:where_ast] = NoBrainer::Criteria::Where::MultiOperator.new(:or,
                                         queries.map { |q| q.options[:where_ast] }).simplify
    all_docs = merged_query.to_a

    queries.each do |q|
      where_ast = q.options[:where_ast]

      # Some sanitiy checks. We are still missing a bunch, like sorting,
      # skipping, limits, etc.
      raise NotImplementedError unless where_ast.op == :and
      raise NotImplementedError unless where_ast.clauses.size == 1
      in_op = where_ast.clauses.first
      raise NotImplementedError unless in_op.op == :in
      raise NotImplementedError unless in_op.model == merged_query.model
      raise NotImplementedError unless in_op.key_modifier == :scalar
      raise NotImplementedError unless in_op.key_path.size == 1

      docs = all_docs.select { |doc| in_op.value.include?(doc.__send__(in_op.key_path.first)) }
      q._override_cache(docs)
    end
  end
end
```

To use it with your example:

```ruby
posts = Post.all.to_a
NoBrainer.eager_load_queries(posts.map(&:authors))
posts.each do |post| # won't trigger queries
  puts "#{post.title.inspect} by #{post.authors.map(&:name).join(', ')}"
end
```

The way it works is by merging all the `:in` queries together with a `:or`, and then feeding the results to the correct queries. This works because in your code, the `@authors` query is cached, and its results are cached.

Let me know if you like this solution.

**Comment by CodeMonkeySteve** [comment]
Sorry it's taken so long to respond, it took a bit of research to understand how that code works.  I guess I'm surprised that adding this as an association is difficult, as the underlying RQL is almost the same as the belongs-to-one case.  I think this would solve my problem, although it's a bit heavy-weight since I don't need to merge arbitrary queries, just the fetch by primary key.  It would be nice to work it into the regular `eager_load` method, though.

But the more I think about it, the more it seems like there's an impedance mismatch between the classic SQL belongs_to/has_many associations and Ruby's system of references and garbage collection. I'm thinking about diverging from the ActiveRecord paradigm and implementing associations as references accessed through typed proxy classes.  This would take advantage of RethinkDB's array and set support, without the need for join tables (and hacks to preserve order), while still having the same storage and performance characteristics.

This is probably outside of the scope of NoBrainer, so I'll look at implementing my idea as a separate rubygem.  It's also way outside of the scope of this feature request, so I'll close the issue.  Thanks for all your help.
