### ISSUE TITLE
Disable table creation

### ISSUE THREAD

**Issue by scottrobertson** [nviennot/nobrainer#243]
Hey

Is there a way to fully disable NoBrainer from creating tables? We are having big issues with duplicate tables being created when under high load and a proxy restarts.

**Comment by nviennot** [comment]
To disable auto creation of database and tables, add this code in your app initializer after configuring NoBrainer:

```ruby
NoBrainer::QueryRunner.stack.delete(NoBrainer::QueryRunner::DatabaseOnDemand)
NoBrainer::QueryRunner.stack.delete(NoBrainer::QueryRunner::TableOnDemand)
```

**Comment by scottrobertson** [comment]
Thank you @nviennot

**Comment by nviennot** [comment]
Welcome :))
