### ISSUE TITLE
About multi-tenant model and common database

### ISSUE THREAD

**Issue by extem** [nviennot/nobrainer#252]
I have a question about designing a multi-tenant model.
Create the following DB and table.

common_db.users ... Common DB
user1_db.foo_tables ... DB of each tenant
user2_db.foo_tables ... 
user3_db.foo_tables ... 
user4_db.foo_tables ... 
 
Create the following model.

app/modes
 common_db.rb
 foo_tables.rb
 
rails starts for each tenant.

NoBrainer.sync_schema will create a users table for each tenant.
Is there a way to prevent this?
Access to common_db is
NoBrainer.run_with (: db => 'common_db') {...}

In the previous version, it seems that the model had a function to specify DB with sotre_in.

I would appreciate it if you could tell me.
best regards

**Comment by nviennot** [comment]
The "Model Specific Behavior" section of http://nobrainer.io/docs/multi_tenancy/ explains how to do what you wish
