### ISSUE TITLE
Error with Cucumber testing

### ISSUE THREAD

**Issue by mindtrades** [nviennot/nobrainer#67]
Hi I get error when i try to use cucumber with rethinkdb connected via no-brainer.
Error:
No known ORM was detected!  Is ActiveRecord, DataMapper, Sequel, MongoMapper, Mongoid, Moped, or CouchPotato, Redis or Ohm loaded? (DatabaseCleaner::NoORMDetected)

Cucumber requires database cleaner as a gem . what do i do about this?

**Comment by zedtux** [comment]
Here is the correct link to the documentation: http://nobrainer.io/docs/db_management/
