### ISSUE TITLE
carrierwave and nobrainer ?

### ISSUE THREAD

**Issue by zedtux** [nviennot/nobrainer#94]
I'm now working on a file upload feature in my project and I'd like to store the documents in RethinkDB.

After some researches I've found that [carrierwave](https://github.com/carrierwaveuploader/carrierwave) should be the best option. This gem has a lot of supported ORM but I haven't found any one for RethinkDB (I have check few minutes about [DataMapper](http://datamapper.org) but I haven't found anything about nobrainer and RethinkDB).

 * Do you know about something existing to perform this ?
 * In the case there's nothing, do you have some direction to implement it ?

Thanks in advance :)

**Comment by zedtux** [comment]
@nviennot any plan on this request ?

**Comment by nviennot** [comment]
I have no plan.

however there's an attempt here: https://github.com/katafrakt/carrierwave-nobrainer
I have no clue if it's good or not though.

**Comment by zedtux** [comment]
Thank you for the link.

Do we keep the issue open ?
